version: '3'
services:
  site:
    environment:
      JEKYLL_ENV: production
    image: jekyll/jekyll
    volumes:
      - .:/srv/jekyll
    ports:
      - 4000:4000
    command: >
      jekyll serve \
        --watch \
        --force_polling
